### ISSUE TITLE
Adrien's review

### ISSUE THREAD

**Issue by aallorant** [math241s24/project01-team-holiday#3]
---
name: Adrien's review
about: Review of project proposal
title: Proposal review
---

### proposal.qmd

Your proposal is good, although a bit succinct and missing some key elements:

- You need to include inline code that loads the required libraries to read in your dataset (which should be saved in the data folder).

- You want to describe the variables in your dataset- at least the one you will use for your analyses- variable name, type, categories if factor, range if numeric.

Your two research questions are good, although it would be great to explicitly mention how you will answer them, specifically:
- which variables would be involved?
- how would you process/visualize them?

### about.qmd

You want to update the `About` section of your website.
  
### _quarto.yml

You want to update the `yml` document.

Specifically, you want to update the website section of the `yml`:

```
website:
  title: Seattle Bike
  navbar:
    right:
      - icon: github
        href: https://github.com/aallorant/project01-seattle-bike
```
